[2024-09-12 23:15:07,064]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-12 23:15:07,482]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-12 23:15:07,641]^;INFO^;224^;_internal.py^;_log()^;[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-12 23:15:07,642]^;INFO^;224^;_internal.py^;_log()^;[33mPress CTRL+C to quit[0m
[2024-09-12 23:16:15,469]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [12/Sep/2024 23:16:15] "GET / HTTP/1.1" 200 -
[2024-09-12 23:16:15,558]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [12/Sep/2024 23:16:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-12 23:16:26,076]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [12/Sep/2024 23:16:26] "GET /predict HTTP/1.1" 200 -
[2024-09-12 23:16:26,149]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [12/Sep/2024 23:16:26] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-12 23:19:37,203]^;ERROR^;1745^;app.py^;log_exception()^;Exception on /predict [POST]
Traceback (most recent call last):
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 113, in predict
    housing_df=data.get_housing_input_data_frame()
AttributeError: 'HousingData' object has no attribute 'get_housing_input_data_frame'
[2024-09-12 23:19:37,219]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [12/Sep/2024 23:19:37] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
